"""empty message

Revision ID: 693d27ba6cdb
Revises: d402500718af
Create Date: 2024-09-09 21:30:58.991594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693d27ba6cdb'
down_revision = 'd402500718af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
