"""empty message

Revision ID: 60109834fba5
Revises: ae524b03930c
Create Date: 2024-09-14 20:55:47.990056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60109834fba5'
down_revision = 'ae524b03930c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
