"""empty message

Revision ID: 61dd5f9550f9
Revises: 88eaef3141c8
Create Date: 2024-09-15 15:47:03.616738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dd5f9550f9'
down_revision = '88eaef3141c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_one', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_two', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_three', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_four', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_four')
        batch_op.drop_column('image_three')
        batch_op.drop_column('image_two')
        batch_op.drop_column('image_one')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
